import { Product } from "../types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Etiquetado para Botella",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinicola/ImgEtiquetadoBotella.png" },
    categoryId: "vinicolas",
    price: 149.99,
  },
  {
    id: "2",
    name: "Botella Borgoña",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinicola/ImgBotellaBorgona.png" },
    categoryId: "vinicolas",
    price: 89.99,
  },
  {
    id: "3",
    name: "Botella Bordalesa",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinicola/ImgBotellaBordalesa.png" },
    categoryId: "vinicolas",
    price: 199.99,
  },
  {
    id: "4",
    name: "Racas para Barrica",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinicola/ImgRacasParaBarrica.png" },
    categoryId: "vinicolas",
    price: 299.99,
  },
  {
    id: "5",
    name: "Alambre para Vino Espumoso",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinicola/ImgAlambreVino.png" },
    categoryId: "vinicolas",
    price: 120.0,
  },
  {
    id: "6",
    name: "Capsulas",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinicola/ImgCapsulas.png" },
    categoryId: "vinicolas",
    price: 85.0,
  },
  {
    id: "7",
    name: "Capsulas para Vino Espumoso",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinicola/ImgCapsulasEspumoso.png" },
    categoryId: "vinicolas",
    price: 450.0,
  },
  {
    id: "8",
    name: "Macro Bins",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-precosecha/ImgMacroBins.png" },
    categoryId: "precosecha",
    price: 580.0,
  },
  {
    id: "9",
    name: "Malla Protectora",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-precosecha/ImgMallaProtectora.png" },
    categoryId: "precosecha",
    price: 45.0,
  },
  {
    id: "10",
    name: "Caja para Cosecha",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-precosecha/ImgCajaCosecha.png" },
    categoryId: "precosecha",
    price: 220.0,
  },
  {
    id: "11",
    name: "Tijeras para Cosecha",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-precosecha/ImgTijerasCosecha.png" },
    categoryId: "precosecha",
    price: 175.0,
  },
  {
    id: "12",
    name: "Cubeta para Cosecha",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-precosecha/ImgCubetaCosecha.png" },
    categoryId: "precosecha",
    price: 175.0,
  },
  {
    id: "13",
    name: "Alambre Galvanizado de Alta Resistencia",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgAlambreGalvanizado.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "14",
    name: "Poste Cabecera",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgPosteCabecera.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "15",
    name: "Kit Ancla Gripple",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgKitAncla.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "16",
    name: "Estacas de Madera",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgEstacasMadera.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "17",
    name: "Clip de Poste Metalico",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgKitPosteMetalico.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "18",
    name: "Ancla APEX - Cable de Acero",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/Screenshot%202026-05-25%20at%208.28.26%20PM.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "19",
    name: "Pinza Tensadora Gripple",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgPinzaTensadora.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "20",
    name: "Cruceta de Acero",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgCrucetaAcero.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "21",
    name: "Candado Gripple Plus",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgCandadoGripple.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "22",
    name: "Postes de Madera",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgPostesMadera.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "23",
    name: "Postes 2 3/4 x 8'",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-vinedo/ImgPosteTresCuartos.png" },
    categoryId: "vinedos",
    price: 175.0,
  },
  {
    id: "24",
    name: "Caja Protectora",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgCajaProtectora.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "25",
    name: "Cinta Verde Agricola",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgCintaVerde.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "26",
    name: "Pistola de Cinta",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgPistolaCinta.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "27",
    name: "Afilador Corona",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgAfilador.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "28",
    name: "Tijera Felco",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgTijeraFelco.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "29",
    name: "Tutor",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgTutor.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "30",
    name: "Protector de plastico",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgProtectorPlastico.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "31",
    name: "Cinta Blanca para Injerto",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgCintaBlanca.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "32",
    name: "Sellador para Planta",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgSelladorPlanta.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "33",
    name: "Serrucho BAHCO",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgSerrucho.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "34",
    name: "Tijera para Poda",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgTijeraPoda.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "35",
    name: "Poste Madera",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgPosteMadera.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "36",
    name: "Navaja para Injertar BAHCO",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgNavaja.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "37",
    name: "Sellador Natural para Planta",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgSelladorNatural.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "38",
    name: "Tijera Dos Manos",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-planta/ImgTijeraDosManos.png" },
    categoryId: "planta",
    price: 175.0,
  },
  {
    id: "39",
    name: "Corcho Natural",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/corchos/ImgCorchoNatural.png" },
    categoryId: "corchos",
    price: 175.0,
  },
  {
    id: "40",
    name: "Corcho Microaglomerado",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/corchos/ImgCorchoMicroaglomerado.png" },
    categoryId: "corchos",
    price: 175.0,
  },
  {
    id: "41",
    name: "Corcho Tecnico 1+1 EVO",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/corchos/ImgCorchoTecnico.png" },
    categoryId: "corchos",
    price: 175.0,
  },
  {
    id: "42",
    name: "Corcho Enhanced",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/corchos/ImgCorchoEnhanced.png" },
    categoryId: "corchos",
    price: 175.0,
  },
  {
    id: "43",
    name: "Conexiones Elevadores",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgConexionesElevadores.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "44",
    name: "Gotero Toro",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgGoteroToro.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "45",
    name: "Manguera para Riego",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgMangueraRiego.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "46",
    name: "Micro Gotero",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgMicroGotero.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "47",
    name: "Espaguetti Irritec",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgEspaguetti.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "48",
    name: "Valvulas",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgValvulas.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "49",
    name: "Conexiones para Riego",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgConexionesRiego.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "50",
    name: "Gotero",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgGotero.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "51",
    name: "T Pro Lock",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgTProlock.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "52",
    name: "Figura Ocho",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgFiguraOcho.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "53",
    name: "Valvula de Acoplamiento",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgValvulaAcoplamiento.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "54",
    name: "Tapon para Gotero",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgTaponGotero.png" },
    categoryId: "riego",
    price: 175.0,
  },
  {
    id: "55",
    name: "Valvula de 3/4 a 1/2",
    image: { uri: "https://hijgomyavxpyrxdrpqnd.supabase.co/storage/v1/object/public/products/material-riego/ImgValvulaTresCuartos.png" },
    categoryId: "riego",
    price: 175.0,
  },
  
];
